# Choose which storage option you wanna use.
# Options: json/mysql
storage-type: "json"

mysql:
  database: "database"
  host: "localhost"
  port: 3306
  username: "user"
  password: "password"
  flags: "?useSSL=false&autoReconnect=true&useUnicode=yes"