name: PlayerTracker
version: ${project.version}
main: lol.hyper.playertracker.PlayerTracker
api-version: 1.16
author: hyperdefined
commands:
  player:
    description: Shows join date and last login time.